### ISSUE TITLE
Mobile Bugs

### ISSUE THREAD

**Issue by ChaseC99** [WICS-UCI/venushacks#159]
Collection of bugs found on the mobile site

**Comment by ChaseC99** [comment]
Bottom has a weird margin cutting off the content
<img width="375" alt="image" src="https://user-images.githubusercontent.com/29494270/155260860-fca5dbc4-fe7f-453d-b398-3a7cffdda056.png">

**Comment by nathantoannguyen** [comment]
not the 2 percent left 💀

**Comment by ChaseC99** [comment]
Closing this since we only have one bug, which now has it's own issue.
