### ISSUE TITLE
Mobile Bug: Bottom has a weird margin cutting off the content

### ISSUE THREAD

**Issue by ChaseC99** [WICS-UCI/venushacks#160]
Bottom has a weird margin cutting off the content
<img width="375" alt="image" src="https://user-images.githubusercontent.com/29494270/155260860-fca5dbc4-fe7f-453d-b398-3a7cffdda056.png">

_Originally posted by @ChaseC99 in https://github.com/WICS-UCI/venushacks/issues/159#issuecomment-1048435449_

**Comment by alanchangxyz** [comment]
fixed on live 👍
