### ISSUE TITLE
Website Bug: Fix Screen Resizing Issue

### ISSUE THREAD

**Issue by emidoan** [WICS-UCI/venushacks#164]
Organizer photos get cut off if you go from minimized window to fullscreen:

<img width="1000" alt="Screen Shot 2022-02-22 at 10 15 44 PM" src="https://user-images.githubusercontent.com/69323763/155288713-e6647bf3-0778-457f-a7b9-d0695428b964.png">

Not really a big issue, but something to tackle if we want.

**Comment by sirAvent** [comment]
Seems to be an issue with the `Parallax` component. It has now been removed in #224 and this issue does not appear anymore!
