### ISSUE TITLE
Update Emails

### ISSUE THREAD

**Issue by ChaseC99** [WICS-UCI/venushacks#171]
We can start using email aliases now!

- [x] Update corporate's "venushacks.corporate@gmail.com" to "sponsorships@venushacks.com"
- [x] Figure out what we're using instead of "venushacks@gmail.com". I think it's "contact@venushacks.com"?

**Comment by gracebmanning** [comment]
Any confirmation about replacing the venushacks.uci@gmail.com with contact@venushacks.com?
