### ISSUE TITLE
Make the "Apply" buttons a single component

### ISSUE THREAD

**Issue by ChaseC99** [WICS-UCI/venushacks#172]
Right  now it is 2 buttons with `<a>` tags. This is glitchy and clicking doesn't always work when you don't click exactly on the text.

Create a new `<ApplyButton>` component that takes in props for the URL and Text.

Inside the component, can look something like this. You'll also need to update the styling accordingly.
```jsx
<Button href={URL} target="_blank" id="apply-hacker-btn">
        {text}
</Button>
```

**Comment by nathantoannguyen** [comment]
I made the changes you stated, but when I tested and clicked on the button without clicking directly on the text, the button isn't clicked. Here's the code that I have if you could look at it.

ApplyButton(URL, text) {
    return (
      <Button className="apply-btn">
        <a
          href={URL} target="_blank" id="apply-hacker-btn">
          {text}
        </a>
      </Button>
      )
  }
  
                        {this.ApplyButton("https://airtable.com/shr1Etr4Typ3FEqBc", "Apply as a Hacker")}
                      {this.ApplyButton("https://airtable.com/shr5Y9x5ocJaJL52j", "Apply as a Mentor")}

**Comment by nathantoannguyen** [comment]
Completed alongside #157
