### ISSUE TITLE
Add More FAQs 

### ISSUE THREAD

**Issue by emidoan** [WICS-UCI/venushacks#175]
**Question:** Can international students participate?
**Answer:** Yes! International students will be able to participate virtually.

**Question:** Can I attend in-person?
**Answer:** In-person attendance is limited to only official UCI students with proper UCI identification. However, anyone can attend virtually!

**Comment by nathantoannguyen** [comment]
Question: Can international students participate?
Answer: VenusHacks is limited to hackers within the United States.

Question: Can I attend in-person?
Answer: In-person attendance is limited to only official UCI students with proper UCI identification. However, anyone can attend virtually!
