### ISSUE TITLE
Show + Update Schedule Page to 2022 Schedule

### ISSUE THREAD

**Issue by emidoan** [WICS-UCI/venushacks#184]
Once schedule is (mostly) finalized, show + update schedule page to 2022 schedule. Will include link to spreadsheet here soon.

**Comment by nathantoannguyen** [comment]
https://docs.google.com/spreadsheets/d/1COLZdyU7XeenRDFKCBEN9xGJJeRYH3DdYQGU_gH9seg/edit#gid=1753981004
