### ISSUE TITLE
Add route to Anonymous Incident Form

### ISSUE THREAD

**Issue by nathantoannguyen** [WICS-UCI/venushacks#198]
Add route to [form](https://docs.google.com/forms/d/e/1FAIpQLSepDdiImhchD7eBsRwiQk9a9TG5nQwdtPumrDUKEeX3tZLaKw/viewform?usp=sf_link)

Redirect /report directly to form link

**Comment by ChaseC99** [comment]
You'll want to add something like this to `App.js`
```jsx
<Route exact path={`/report`} component={()=>{
    window.location.replace(redirect.url); 
    return null;
}} />
```
Note: make sure it is about the NotFound route, otherwise this won't work.

**Comment by gracebmanning** [comment]
@ChaseC99 what did you mean by "make sure it is about the NotFound route"? Did you mean _above_ or should I be integrating these two Routes

**Comment by nathantoannguyen** [comment]
I'm dm you on slack @gracebmanning

**Comment by ChaseC99** [comment]
> @ChaseC99 what did you mean by "make sure it is about the NotFound route"? Did you mean _above_ or should I be integrating these two Routes

Ah yeah sorry I meant "above".
