### ISSUE TITLE
VenusHacks Migration to Next.js App Router Application

### ISSUE THREAD

**Issue by samderanova** [WICS-UCI/venushacks#243]
For the rewrite of the VenusHacks site, we plan on migrating the current VenusHacks site to Next.js App Router. We'll want to separate this out into smaller tasks as follows:

- [x] Set up blank Next.js App Router application
- [x] Set up pre-commit hooks
- [x] #244
- [x] Switch indentation size from spaces to tabs
- [x] Move redirects to `next.config.js`

**Comment by alanchangxyz** [comment]
don't think there were any redirects to migrate for this so marking the last one as done for now; but for reference for redirects, https://github.com/HackAtUCI/irvinehacks-site-2024/blob/main/apps/site/next.config.js

**Comment by samderanova** [comment]
Sounds good. This pretty much completes the structural migration to App Router, so I'll be closing this issue.
