### ISSUE TITLE
Navigation Sidebar

### ISSUE THREAD

**Issue by alanchangxyz** [WICS-UCI/venushacks#249]
We'll need to build a new navbar that drops in from the left side instead of sitting at the top of the page. It has new icons for each of the pages and would ideally be animated as a priority since it's one of the more viewed components on the site.

The animations here will probably be the most fun part; looking online, we can make something similar to https://codesandbox.io/p/sandbox/framer-motion-sidebar-finished-x07lz?file=%2Fsrc%2Findex.js for reference

See VH Website Figma/Mockup for what this looks like

*To build:*
- Sidebar with links to Home, Schedule, Resources, Incident Form, Devpost (last two can be placeholders until we get the actual links)
- Nice to have: Animations via Framer Motion

**Comment by alanchangxyz** [comment]
Side note: we probably need a workshops page link here too

**Comment by samderanova** [comment]
Also, as @alanchangxyz mentioned in #243, this is where we'll need to specify redirects for all of our external links.

**Comment by alanchangxyz** [comment]
Looks like navbar got moved back to top anchor lol, but we can still try to implement some of the ideas from that codesandbox

**Comment by alanchangxyz** [comment]
#262
